name: JSON check
on:
  pull_request:
    paths:
      - '**.json'

env:
  BASE: "Ancd"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\variables.json$"
